# Generated by Django 4.2.3 on 2023-08-28 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_unitconversion_material_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='amount',
            new_name='totalprice',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='price',
            new_name='totalquantity',
        ),
        migrations.RemoveField(
            model_name='material',
            name='remaining_amount',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.material')),
            ],
        ),
    ]
