# Generated by Django 4.2.3 on 2023-08-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_amount_material_totalprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='address',
        ),
        migrations.RemoveField(
            model_name='material',
            name='image',
        ),
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='purchase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
