# Generated by Django 4.2.3 on 2023-08-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_material_address_remove_material_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.unitconversion'),
        ),
    ]
