# Generated by Django 4.2.3 on 2023-08-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_purchase_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='unit',
        ),
    ]
