# Generated by Django 4.2.3 on 2023-08-29 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_purchase_cheque_number_purchase_is_cheque_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='address',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='cheque_number',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_cheque_paid',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment_method',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('is_cheque_paid', models.BooleanField(default=False)),
                ('cheque_number', models.CharField(blank=True, max_length=20, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.seller')),
            ],
        ),
    ]
