# Generated by Django 4.2.3 on 2023-08-29 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_amount_payment_amount_to_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.payment'),
        ),
    ]
