# Generated by Django 4.2.3 on 2023-08-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_purchase_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturedproduct',
            name='electricity_charges',
        ),
        migrations.RemoveField(
            model_name='manufacturedproduct',
            name='labor_charges',
        ),
        migrations.RemoveField(
            model_name='manufacturedproduct',
            name='other_expenses',
        ),
        migrations.RemoveField(
            model_name='manufacturedproduct',
            name='quantity_produced',
        ),
        migrations.RemoveField(
            model_name='manufacturedproduct',
            name='transport_charges',
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.manufacturedproduct')),
            ],
        ),
    ]
