# Generated by Django 4.2.3 on 2023-08-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_manufacturedproduct_electricity_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='electricity_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='labor_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='transport_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
