# Generated by Django 4.2.3 on 2023-08-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productionrun_electricity_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='other_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
