# Generated by Django 4.2.3 on 2023-09-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productionrun_other_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturedproduct',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='manufacturedproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
