# Generated by Django 4.2.3 on 2023-09-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_manufacturedproduct_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturedproduct',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='manufacturedproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
