# Generated by Django 4.2.3 on 2023-09-03 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_sell_price_after_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.discountcode'),
        ),
    ]
