# Generated by Django 4.2.3 on 2023-09-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_buyer_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
