# Generated by Django 4.2.3 on 2023-09-03 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_agent_sell_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='commission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.commissioncode'),
        ),
    ]
