# Generated by Django 4.2.3 on 2023-09-03 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_sell_agent_alter_sell_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='buyer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.buyer'),
        ),
    ]
