# Generated by Django 4.2.3 on 2023-09-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_sell_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='commissionvalue',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='discountvalue',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='commission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.commissioncode'),
        ),
    ]
