# Generated by Django 4.2.3 on 2023-09-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_sell_discountvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='discountvalue',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
    ]
