# Generated by Django 4.2.3 on 2023-09-03 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_sell_price_after_commission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('commission', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('agent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.agent')),
            ],
        ),
    ]
