# Generated by Django 4.2.3 on 2023-09-04 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_agentcommission_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='totalpayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='buyerpayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='totalpayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BuyerPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField(blank=True, default=None, null=True)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.buyer')),
            ],
        ),
    ]
