# Generated by Django 4.2.3 on 2023-09-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_agent_totalpayment_agentcommission_buyerpayment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentcommission',
            old_name='totalpayment',
            new_name='totalamount',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='totalpayment',
        ),
        migrations.AddField(
            model_name='buyerpayments',
            name='totalamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
