# Generated by Django 4.2.3 on 2023-09-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_agentcommission_agentbuyprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='price_after_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='price_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
